# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-14 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaportalapp', '0002_auto_20190714_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='day_of_the_event',
            new_name='day',
        ),
    ]
