# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-15 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import mediaportalapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaportalapp', '0004_auto_20190715_0034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': '\u041a\u0430\u043b\u0435\u043d\u0434\u0430\u0440\u044c', 'verbose_name_plural': '\u041a\u0430\u043b\u0435\u043d\u0434\u0430\u0440\u044c'},
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default=b'', upload_to=mediaportalapp.models.generate_filename, verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=b'', verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default=b'', max_length=120, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DateField(help_text='\u0414\u0435\u043d\u044c \u0441\u043e\u0431\u044b\u0442\u0438\u044f', verbose_name='\u0414\u0435\u043d\u044c \u0441\u043e\u0431\u044b\u0442\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(help_text='\u041a\u043e\u043d\u0435\u0446', verbose_name='\u041a\u043e\u043d\u0435\u0446'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, help_text='\u0417\u0430\u043c\u0435\u0442\u043a\u0438', null=True, verbose_name='\u0417\u0430\u043c\u0435\u0442\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(help_text='\u041d\u0430\u0447\u0430\u043b\u043e', verbose_name='\u041d\u0430\u0447\u0430\u043b\u043e'),
        ),
    ]
