# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-15 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaportalapp', '0005_auto_20190715_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('slug', models.SlugField(default=b'', verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
            ],
            options={
                'verbose_name': '\u041a\u0430\u043b\u0435\u043d\u0434\u0430\u0440\u044c',
                'verbose_name_plural': '\u041a\u0430\u043b\u0435\u043d\u0434\u0430\u0440\u0438',
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': '\u0421\u043e\u0431\u044b\u0442\u0438\u0435', 'verbose_name_plural': '\u0421\u043e\u0431\u044b\u0442\u0438\u044f'},
        ),
    ]
