# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-15 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaportalapp', '0006_auto_20190715_1155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
