# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-16 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mediaportalapp', '0007_delete_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDownloading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'', max_length=120, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('slug', models.SlugField(default=b'', verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
                ('notes', models.TextField(blank=True, help_text='\u0417\u0430\u043c\u0435\u0442\u043a\u0438', null=True, verbose_name='\u0417\u0430\u043c\u0435\u0442\u043a\u0438')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, help_text='\u0412\u0432\u043e\u0434\u0438\u0442\u044c \u0442\u043e\u043b\u044c\u043a\u043e URL-\u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b', verbose_name='\u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c \u0432\u0438\u0434\u0435\u043e')),
            ],
            options={
                'verbose_name': '\u0412\u0438\u0434\u0435\u043e\u043e\u0431\u0437\u043e\u0440',
                'verbose_name_plural': '\u0412\u0438\u0434\u0435\u043e\u043e\u0431\u0437\u043e\u0440\u044b',
            },
        ),
    ]
