# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-16 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaportalapp', '0008_videodownloading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodownloading',
            name='slug',
        ),
        migrations.AddField(
            model_name='videodownloading',
            name='url',
            field=models.CharField(default=b'', max_length=200, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
    ]
