# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-17 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import mediaportalapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaportalapp', '0009_auto_20190716_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_main',
            field=models.ImageField(default=b'', upload_to=mediaportalapp.models.generate_filename, verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f'),
        ),
    ]
