# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-17 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import mediaportalapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaportalapp', '0010_event_image_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_main',
            field=models.ImageField(default=b'', upload_to=mediaportalapp.models.generate_filename, verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='raiting',
            name='image',
            field=models.ImageField(default=b'', upload_to=mediaportalapp.models.generate_filename, verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='raiting',
            name='image_main',
            field=models.ImageField(default=b'', upload_to=mediaportalapp.models.generate_filename, verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default=b'', upload_to=mediaportalapp.models.generate_filename, verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f'),
        ),
    ]
