# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-18 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import mediaportalapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaportalapp', '0013_auto_20190717_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_main',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image_main',
        ),
        migrations.RemoveField(
            model_name='raiting',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='raiting',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='raiting',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='raiting',
            name='image_main',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=mediaportalapp.models.generate_filename, verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f'),
        ),
    ]
