# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-18 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mediaportalapp', '0014_auto_20190718_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='raiting',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='videodownloading',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
