# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-19 08:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mediaportalapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mediaportalapp', '0015_auto_20190718_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleOtrasli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('slug', models.SlugField(verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
                ('image', models.ImageField(upload_to=mediaportalapp.models.generate_filename, verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f')),
                ('content', models.TextField(verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442')),
                ('author', models.TextField(default=b'', verbose_name='\u0410\u0432\u0442\u043e\u0440')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='\u041b\u0430\u0439\u043a\u0438')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryOtrasli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('slug', models.SlugField(verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
            ],
            options={
                'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f',
                'verbose_name_plural': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438',
            },
        ),
        migrations.AddField(
            model_name='articleotrasli',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediaportalapp.CategoryOtrasli', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='articleotrasli',
            name='users_reaction',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='\u041a\u0442\u043e \u043e\u0442\u0440\u0435\u0430\u0433\u0438\u0440\u043e\u0432\u0430\u043b \u043d\u0430 \u043f\u043e\u0441\u0442'),
        ),
    ]
