# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-27 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaportalapp', '0017_event_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodownloading',
            name='url',
            field=models.CharField(default=b'', help_text='\u0412\u0432\u043e\u0434\u0438\u0442\u044c \u0442\u043e\u043b\u044c\u043a\u043e URL-\u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b', max_length=200, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
    ]
